name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev-deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #  Install Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #  Install deps
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      #  Build Angular
      - name: Build Angular
        run: |
          cd frontend
          npm run build -- --configuration production

      #  Deploy prebuilt app
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BAY_0DA833D00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          skip_app_build: true
          app_location: "frontend"
          api_location: ""

          # ðŸ”¥ MOST IMPORTANT LINE
          app_artifact_location: "frontend/dist/docvault-frontend"
